[servers:children]
webservers

[webservers]
server1 ansible_host=111.88.147.9 ansible_user=mrkuzy9999 ansible_ssh_private_key_file=~/.ssh/id_rsa
server2 ansible_host=111.88.150.198 ansible_user=mrkuzy9999 ansible_ssh_private_key_file=~/.ssh/id_rsa

[webservers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
