- name: Setup servers
  hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    docker_dependencies:
      - apt-transport-https
      - ca-certificates
      - gnupg

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
