- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    docker_dependencies:
      - apt-transport-https
      - ca-certificates
      - gnupg

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

  roles:
    - geerlingguy.pip
    - geerlingguy.docker