- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - geerlingguy.pip
    - geerlingguy.docker